server.port=8081
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Enter your PostgreSQL database password}
spring.datasource.driver-class-name=org.postgresql.Driver

# Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=Enter your Gmail address
spring.mail.password=Enter your Gmail app password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=3000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=3000
spring.mail.properties.mail.smtps.connectiontimeout=3000
spring.mail.properties.mail.smtps.timeout=3000
spring.mail.properties.mail.smtps.writetimeout=3000

# App
app.mail.from=Enter your Gmail address
app.mail.from-name=NexusMart
