spring.application.name=payment-service
server.port=8085

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:Enter your PostgreSQL password here}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL Init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Razorpay Configuration
razorpay.key.id=Enter your Razorpay key ID here
razorpay.key.secret=Enter your Razorpay key secret here

# JWT Configuration (Match auth-service)
jwt.secret=Enter your JWT secret key here
