spring.application.name=payment-service
server.port=8085

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# SQL Init
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Razorpay Configuration (Mock credentials for test)
razorpay.key.id=rzp_test_SvQDlSXovmsr5q
razorpay.key.secret=Z1WlTl43NZvCYNAul6DoTuKL

# JWT Configuration (Match auth-service)
jwt.secret=my_super_secret_key_for_ecommerce_app_12345
